//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.GioHang = new HashSet<GioHang>();
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
        }
    
        public int Id { get; set; }
        public string Ten { get; set; }
        public Nullable<double> Gia { get; set; }
        public string ThongTin { get; set; }
        public Nullable<int> LoaiSP_ID { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<double> LuotMua { get; set; }
        public string Kieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHang { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
    }
}
